# Site settings
title: Tadej Novak
email: tadej@tano.si
description: Tadej Novak's personal web page
url: "https://tano.si"
cdn_url: "https://cdn.tano.si/personal"
baseurl: ""

twitter_username: ntadej
github_username: ntadej

# Build settings
production: false
incremental: true
source: src
destination: public
layouts_dir: _tano-style/html/_layouts
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->
exclude: []

gems:
  - jekyll-assets
  - jekyll-archives
  - jekyll-feed

assets:
  cache: .asset-cache
  compress:
    css: true
    js: true
  features:
    automatic_img_alt: false
    automatic_img_size: false
  sources:
    - _assets/scripts
    - _assets/sass
    - _assets/images
    - _tano-style
    - _tano-style/node_modules

feed:
  path: feed.rss

jekyll-archives:
  enabled: all
  layouts:
    year: personal/year
    month: personal/month
    day: personal/day
    tag: personal/tag
    category: personal/category
