# Site settings
title: Tadej Novak
email: tadej@tano.si
description: >
  ... opis ...
baseurl: ""
url: "http://tano.si"
vlc-qt_url: "http://vlc-qt.tano.si"
twitter_username: ntadej
github_username:  ntadej

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->
exclude: [Gemfile, Gemfile.lock, README.md, src]

assets:
  version: 1
  cache: false
  compress:
    css:  sass
    js:   uglifier
