# Site settings
title: Tadej Novak
email: tadej@tano.si
description: >
  Tadej Novak's personal web page
baseurl: ""
url: "https://tano.si"
vlc-qt_url: "https://vlc-qt.tano.si"
cdn_url: "https://cdn.tano.si/tano"
twitter_username: ntadej
github_username:  ntadej

# Build settings
production: false
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->
exclude: [bower_components, Gemfile, Gemfile.lock, LICENSE.md, Rakefile, README.md, src, vendor]

assets:
  cache: false
  compress:
    css: true
    js:  true
  features:
    automatic_img_alt:  false
    automatic_img_size: false
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - bower_components
